"""
De-para: categorias do Splitwise (export em italiano) -> categoria/subcategoria do app novo.
"""

CATEGORY_MAP = {
    "Alimentari": ("Alimentação", "Mercado"),
    "Affitto": ("Moradia", "Moradia"),
    "Pulizie": ("Moradia", "Limpeza"),
    "Casa - Altro": ("Moradia", "Moradia"),
    "Carburante": ("Transporte", "Combustível"),
    "Energia elettrica": ("Moradia", "Utilities"),
    "Riscaldamento/gas": ("Moradia", "Utilities"),
    "TV/Telefono/Internet": ("Moradia", "Utilities"),
    "Auto": ("Transporte", "Manutenção"),
    "Casalinghi": ("Moradia", "Limpeza"),
    "Arredamento": ("Moradia", "Acessórios"),
    "Ristorante": ("Alimentação", "Restaurante"),
    "Cibo e bevande - Altro": ("Alimentação", "Delivery"),
    "Spese mediche": ("Saúde", "Farmácia"),
    "Manutenzione": ("Moradia", "Manutenção"),
    "Elettronica": ("Discricionário", "Eletrônicos"),
    "Taxi": ("Transporte", "Passagens"),
    "Utenze - Altro": ("Moradia", "Utilities"),
    "Alcolici": ("Alimentação", "Bebidas"),
    "Regali": ("Discricionário", "Presentes"),
    "Generali": ("Outros gastos", "Geral"),
    "Assicurazione": ("Transporte", "Manutenção"),
    "Spese personali - Altro": ("Discricionário", "Outros"),
    "Trasporti - Altro": ("Transporte", "Outros"),
    "Mutuo": ("Moradia", "Moradia"),
    "Abbigliamento": ("Discricionário", "Roupas"),
    "Bicicletta": ("Transporte", "Manutenção"),
    "Cinema": ("Lazer", "Geral"),
    "Sport": ("Lazer", "Geral"),
}
